[package]
name = "portfolio_yew"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
serde = "1.0.197"
serde_json = "1.0.114"
stylist = { version = "0.13.0", features = ["yew", "parser"]}
wasm-bindgen = "0.2.91"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
